name: Skopue
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: |
        sudo apt update -y

    - name: targz
      run: |
        unzip myapp.zip
        chmod -R 777 .
        tar --warning=no-file-changed --ignore-failed-read -czvf myapp.tar.gz --owner=0 --mode='u+X' -C "$PWD" completions src configure Makefile install sse main run loop
        ls

    - name: Upload Artifact  
      uses: actions/upload-artifact@v4  
      with:  
        name: myapp
        path: |
          myapp.tar.gz

    - name: Test
      run: |
        ./install
        ./proxychains4 curl ifconfig.me


